### ISSUE TITLE
macOS下透明效果无法正常生效的问题

### ISSUE THREAD

**Issue by JasonXu134590** [SimonShiki/Typability#2]
### 在macOS下，透明效果似乎无法正常生效，导致窗口部分为纯白色，在暗黑模式下一些内容无法正常显示。
<img width="586" alt="b0e1abd5e48028ab8d46cf039421fb8d" src="https://user-images.githubusercontent.com/57546109/211461294-490dab39-d148-400d-b197-570eb260e39c.jpg">
<img width="586" alt="b0e1abd5e48028ab8d46cf039421fb8d" src="https://user-images.githubusercontent.com/57546109/211461271-ab05bff9-857d-47c4-8d84-f63b4f9f8d94.png">

**Comment by SimonShiki** [comment]
Fixed
