### ISSUE TITLE
Milkdown Slash commands

### ISSUE THREAD

**Issue by nickbe** [SimonShiki/Typability#76]
Is it possible to enable the milkdown / slash commands and use them?
(or any other extensions)

**Comment by SimonShiki** [comment]
The slash plugin is currently not integrated into Typability. I can add it in the next release if you need it.

**Comment by nickbe** [comment]
That would be brilliant. 
The editor - once it runs - looks very sleek indeed. And since its loading time is quite fast it would be very useful

**Comment by SimonShiki** [comment]
slash support now added in the latest commit.

**Comment by nickbe** [comment]
Nice one. Thank you. Now I only have to make it run again at all 😆
